#PROJECT EULER PROBLEM 2
#EACH NEW TERM IN THE FIBONACCI SEQUENCE IS GENERATED BY ADDING THE PREVIOUS TWO TERMS. BY STARTING WITH 1 AND 2, THE FIRST 10 TERMS WILL BE:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, …
#BY CONSIDERING THE TERMS IN THE FIBONACCI SEQUENCE WHOSE VALUES DO NOT EXCEED FOUR MILLION, FIND THE SUM OF THE EVEN-VALUED TERMS.

SumOfEvenFibonacci = 0
nums = []
a = 0
b = 1
while True:
    c = a + b
    if c > 4000000:
        break
    nums.append(c)
    a = b
    b = c
for i in nums:
    if i % 2 == 0:
        SumOfEvenFibonacci = SumOfEvenFibonacci + i

print SumOfEvenFibonacci
